### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by vkmel** [boundstate/yii2-mailgun#12] opened 2019-10-25 18:44 UTC
I am getting this error and it is related to the recent update done 17 days ago.. 

Argument 2 passed to Mailgun\Mailgun::__construct() must be an instance of Http\Client\HttpClient or null, string given, called in /opt/bitnami/apache2/htdocs/vendor/boundstate/yii2-mailgun/Mailer.php on line 103

Could you please help me figure out how to solve this? Thank you.

**Comment by blacksmoke26** [comment] 2019-10-28 21:33
Same issue. My whole project mail system is broken

**Comment by blacksmoke26** [comment] 2019-10-28 21:38
![image](https://user-images.githubusercontent.com/425744/67720168-153af580-f9f5-11e9-9fc3-fd593edf637d.png)
Getting the above error! (also other errors)

**Comment by mikejpeters** [comment] 2019-10-29 00:00
This should be fixed in the [v1.0.0 release](https://github.com/boundstate/yii2-mailgun/releases/tag/v1.0.0)

**Comment by vkmel** [comment] 2019-10-29 15:50
I updated to v1.0.0 and also installed buzz and nyholm/psr7. But, I now receive the 
Error
Call to undefined method Mailgun\Mailgun::post()
1. in /opt/bitnami/apache2/htdocs/vendor/boundstate/yii2-mailgun/src/Mailer.php at line 82

**Comment by mikejpeters** [comment] 2019-10-29 17:25
@vkmel sorry about that, please try [v1.0.1](https://github.com/boundstate/yii2-mailgun/releases/tag/v1.0.1) and let me know if the issue is resolved.

I don't use Yii2 much anymore so it's difficult for me to test the full functionality. However I'm slowly adding unit tests as I make these fixes to hopefully make things a more stable & maintainable.

**Comment by vkmel** [comment] 2019-10-30 22:39
I updated to 1.0.1 and everything works well!! Thank you for your time and help.

**Closed as completed** 2019-10-30 22:39 UTC
Labels: bug
